## 🧪 Example of Implementation

### 📊 Data Generation
We generate a synthetic dataset suitable for classification to clearly demonstrate model fitting and evaluation.

### 🏋️‍♂️ Training and Evaluation
We train each classifier:

- `LinearSVC`
- `SVC` with RBF kernel
- `NuSVC`

on the training data, then evaluate their accuracy on the test set to compare performance.

### 🔧 Experimentation
Experiment with parameters such as:

- `C` (regularization strength)
- `kernel` type

Observe how accuracy changes.  
For more complex datasets, use **Grid Search** or **Random Search** to systematically optimize hyperparameters.


In [3]:
import numpy as np
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC, SVC, NuSVC
from sklearn.metrics import accuracy_score

# Step 1: Create a synthetic classification dataset
X, y = make_classification(n_samples=500, n_features=10, n_informative=5,n_redundant=2, n_clusters_per_class=1,random_state=42)

# Step 2: Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=42)

# Step 3: Train a LinearSVC model (linear kernel only)
linear_clf = LinearSVC(random_state=42, max_iter=10000)
linear_clf.fit(X_train, y_train)
y_pred_linear = linear_clf.predict(X_test)
acc_linear = accuracy_score(y_test, y_pred_linear)
y_pred_linear_train = linear_clf.predict(X_train)
acc_linear_train = accuracy_score(y_train, y_pred_linear_train)
print(f"LinearSVC Accuracy: {acc_linear:.2f}")

# Step 4: Train an SVC with the default RBF kernel
rbf_clf = SVC(kernel='rbf', C=1.0, gamma='scale', random_state=42)
rbf_clf.fit(X_train, y_train)
y_pred_rbf = rbf_clf.predict(X_test)
acc_rbf = accuracy_score(y_test, y_pred_rbf)
print(f"SVC (RBF) Accuracy: {acc_rbf:.2f}")

# Step 5: Train a NuSVC (RBF kernel by default)
nu_clf = NuSVC(nu=0.5, kernel='rbf', gamma='scale', random_state=42)
nu_clf.fit(X_train, y_train)
y_pred_nu = nu_clf.predict(X_test)
acc_nu = accuracy_score(y_test, y_pred_nu)
print(f"NuSVC Accuracy: {acc_nu:.2f}")

# Optional: Experiment with a polynomial kernel
poly_clf = SVC(kernel='poly', degree=3, C=1.0, gamma='scale', random_state=42)
poly_clf.fit(X_train, y_train)
y_pred_poly = poly_clf.predict(X_test)
acc_poly = accuracy_score(y_test, y_pred_poly)
print(f"SVC (Poly) Accuracy: {acc_poly:.2f}")



LinearSVC Accuracy: 0.99
SVC (RBF) Accuracy: 0.99
NuSVC Accuracy: 1.00
SVC (Poly) Accuracy: 0.99


# 🌸 Classifying the Iris Dataset with Support Vector Machines (SVM)

The **Iris dataset** is a classical example in machine learning. It involves classifying iris flowers into three distinct species:

- *Iris setosa*
- *Iris versicolor*
- *Iris virginica*

based on four numerical features:

- Sepal length
- Sepal width
- Petal length
- Petal width

---

## 📋 Dataset Overview

- **Number of instances**: 150 (50 samples per species)  
- **Number of features**: 4 (all continuous)  
- **Number of classes**: 3 (multiclass classification problem)

This dataset is simple, clean, and well-balanced. Many machine learning models, including SVMs, can achieve high accuracy on it.

---

## 🤖 Using SVM to Classify Iris Flowers

Support Vector Machines aim to find the **optimal hyperplane** that best separates classes in a high-dimensional space.

Although SVMs are primarily designed for **binary classification**, they can be extended for **multiclass problems** using techniques like **one-vs-rest** or **one-vs-one**—which are often handled internally by libraries like scikit-learn.


In [4]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score

# Step 1: Load the Iris dataset
iris = load_iris()
# Features: Sepal length, sepal width, petal length,petal width
X = iris.data     
y = iris.target    # Target: 0 (setosa), 1 (versicolor), 2 (virginica)

# Step 2: Split into training and testing sets
# Let's use 70% for training and 30% for testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Step 3: Instantiate and train the SVM classifier
# We will use the default kernel='rbf', C=1.0, gamma='scale'
clf = SVC(random_state=42)
clf.fit(X_train, y_train)

# Step 4: Make predictions on the test set
y_pred = clf.predict(X_test)

# Step 5: Evaluate the classifier
cm = confusion_matrix(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)

print("Confusion Matrix:")
print(cm)
print(f"Accuracy: {acc*100:.2f}%")

Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Accuracy: 100.00%
